### ISSUE TITLE
folders_to_zip = ['./world', './world_nether', './world_end']?

### ISSUE THREAD

**Issue by 12iua** [GreshAnt/AutoSaveForBukkitMc#1]
folders_to_zip = ['./world', './world_nether', './world_end']?
no folder call world_end 
it's call world_the_end
![屏幕截图 2024-04-29 113914](https://github.com/GreshAnt/AutoSaveForBukkitMc/assets/142976917/df53ad96-cbbd-4638-beb9-4ce5ee310443)

**Comment by GreshAnt** [comment]
谢谢你，已经修改了

**Comment by GreshAnt** [comment]
感谢

**Comment by 12iua** [comment]
谢谢
